#!/bin/bash

CONFFILE=/etc/syslogd.conf
LOGDIR=/var/log
OPTIONS=()
PIDFILE=/run/syslogd.pid
RESTART=0
SYNC=0

classify() {
  if (( LEVEL > 6 )); then
    FACILITY=debug
  elif [[ $FACILITY == auth* ]]; then
    FACILITY=auth
  elif [[ $FACILITY != @(kern|mail) ]]; then
    FACILITY=daemon
  fi
}

log() {
  if [[ ! -d $LOGDIR/$FACILITY ]]; then
    [[ $FACILITY == debug ]] && return
    mkdir -m 0700 -p "$LOGDIR/$FACILITY"
  fi
  printf '%s %s\n' "$TIME" "$ENTRY" >>"$LOGDIR/$FACILITY/$DATE"
  (( SYNC )) && sync "$LOGDIR/$FACILITY/$DATE"
}

usage() {
  cat >&2 <<EOF
Usage: ${0##*/} [OPTIONS]
Options:
  -b            catch up with old kernel messages in the ring buffer
  -d LOGDIR     set the root log directory, /var/log by default
  -f CONFFILE   set the configuration file, /etc/syslogd.conf by default
  -k            relay syslog messages to the kernel ring buffer
  -p PIDFILE    set the pidfile location, /run/syslogd.pid by default
  -s            sync log files to disk after writing each entry
EOF
  exit 64
}

while getopts :bd:f:kp:s OPTION; do
  case $OPTION in
    b)
      OPTIONS+=('-b')
      ;;
    d)
      LOGDIR=$OPTARG
      ;;
    f)
      CONFFILE=$OPTARG
      ;;
    k)
      classify() (( PEERPID ))
      log() {
        printf '<%d>%s\n' $((FACILITY + LEVEL)) "$ENTRY" >>/dev/kmsg
      }
      OPTIONS+=('-n')
      ;;
    p)
      PIDFILE=$OPTARG
      ;;
    s)
      SYNC=1
      ;;
    *)
      usage
      ;;
  esac
done

(( OPTIND <= $# )) && usage

if [[ -f $CONFFILE ]] && ! source "$CONFFILE"; then
  exit 1
fi

if ! { exec 3>>"$PIDFILE" && flock -n 3; } 2>/dev/null; then
  echo "Failed to lock $PIDFILE; is ${0##*/} already running?" >&2
  exit 1
fi

if read -a STAT </proc/self/stat && (( $$ != STAT[5] )); then
  exec daemon -- "$0" "$@"
  rm -f "$PIDFILE"
  exit 1
fi

echo $$ >"$PIDFILE"
trap 'trap "" TERM && kill -TERM 0 && rm -f "$PIDFILE"' EXIT
trap 'exec -- "$0" "$@"' HUP

if [[ ! -p /dev/stdin ]]; then
  exec < <(syslog "${OPTIONS[@]}" 3>&-)
fi

while read -r PEERPID PEERUID PEERGID FACILITY LEVEL DATE TIME ENTRY; do
  classify && log
done
