#!/bin/bash

set -o pipefail
export PATH=/bin

start() {
  hostname example

  mount -a -n -t proc
  mount -a -n -t cgroup2,devtmpfs,sysfs,tmpfs
  mkdir -m 0755 -p /dev/pts /run/empty
  mkdir -m 1777 -p /run/lock /run/shm
  mount -r -B /run/empty /run/empty

  mount -a -n -t devpts
  ln -f -n -s pts/ptmx /dev/ptmx

  ln -f -n -s /proc/self/fd /dev/fd
  ln -f -n -s fd/0 /dev/stdin
  ln -f -n -s fd/1 /dev/stdout
  ln -f -n -s fd/2 /dev/stderr

  if ZRAM=$(zramctl -f -s 1G); then
    mkswap $ZRAM >/dev/null
    swapon -d $ZRAM
  fi

  mount -n -o remount,ro /
  fsck -a -A -P -T >/dev/null
  if [[ $? -gt 1 ]]; then
    sulogin -p /dev/console
    sync && exec stop reboot
  fi
  mount -o remount,rw /
  mount -a -t nonfs

  if [[ -c /dev/watchdog ]] && exec >/dev/watchdog; then
    trap 'printf V && exit' TERM
    while printf '\0'; do read -t 15; done
  fi <><(:) & disown

  for TTY in /dev/tty[1-6]; do
    daemon -c -r agetty ${TTY#/dev/}
  done

  ip link set lo up
  ip link set eth0 up
  ip address add 192.168.1.2/24 dev eth0
  ip route add default via 192.168.1.1

  syslogd -k
  ssh-keygen -A && $(type -P sshd)
}

listen() {
  if [[ ! -p /dev/initctl ]]; then
    rm -f /dev/initctl
    mkfifo -m 0600 /dev/initctl
  fi

  trap "printf '\0reboot\0' >/dev/initctl" INT
  ctrlaltdel soft

  while read -d '' -r MESSAGE; do
    case "$MESSAGE" in
      halt | poweroff | reboot)
        exec "$0" stop "$MESSAGE"
        ;;
      run\ *)
        eval "${MESSAGE#run }"
        ;;
    esac
  done <>/dev/initctl
}

stop() {
  kill -TERM -1 && sleep 5 && kill -KILL -1
  if swapoff -a && umount -a -r; then
    echo "Remounted filesystems read-only"
  else
    sync && echo "Flushed filesystem writes"
  fi
  exec stop "$@"
}

trap listen EXIT
"${@:-start}"
